import { Client, Post, User } from "@/types"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Ana Lima",
    email: "ana@agencia.com",
    role: "gestor",
    avatar: "",
  },
  {
    id: "u2",
    name: "João Café",
    email: "joao@cafedojoao.com",
    role: "cliente",
    avatar: "",
  },
  {
    id: "u3",
    name: "Maria Fit",
    email: "maria@mariafit.com",
    role: "cliente",
    avatar: "",
  },
]

export const mockClients: Client[] = [
  {
    id: "c1",
    name: "Café do João",
    slug: "cafe-do-joao",
    niche: "Gastronomia",
    toneOfVoice: "Aconchegante e próximo",
    briefing: "Cafeteria artesanal no centro da cidade. Foco em produtos locais e experiência do cliente.",
    color: "#6F4E37",
    socialNetworks: [
      { platform: "instagram", handle: "@cafedojoao" },
      { platform: "facebook", handle: "Café do João" },
    ],
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "c2",
    name: "Maria Fit Studio",
    slug: "maria-fit",
    niche: "Fitness & Saúde",
    toneOfVoice: "Motivacional e técnico",
    briefing: "Studio de pilates e funcional. Público feminino 25-45 anos.",
    color: "#E91E63",
    socialNetworks: [
      { platform: "instagram", handle: "@mariafitstudio" },
      { platform: "tiktok", handle: "@mariafit" },
    ],
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "c3",
    name: "TechVerde",
    slug: "techverde",
    niche: "Tecnologia",
    toneOfVoice: "Profissional e inovador",
    briefing: "Startup de soluções sustentáveis. B2B e B2C.",
    color: "#2E7D32",
    socialNetworks: [
      { platform: "linkedin", handle: "TechVerde" },
      { platform: "instagram", handle: "@techverde" },
    ],
    createdAt: "2024-03-01T10:00:00Z",
  },
]

const today = new Date()
const y = today.getFullYear()
const m = today.getMonth()

export const mockPosts: Post[] = [
  {
    id: "p1",
    clientId: "c1",
    title: "Abertura de semana",
    caption: "☕ Segunda-feira merece um café especial! Venha experimentar nosso novo blend de origem etíope. Grãos selecionados, torra artesanal, sabor único. Te esperamos! ☕",
    network: "instagram",
    status: "publicado",
    scheduledAt: new Date(y, m, 5, 9, 0).toISOString(),
    publishedAt: new Date(y, m, 5, 9, 5).toISOString(),
    hashtags: ["#café", "#cafeteria", "#coffeelovers"],
    comments: [],
    createdAt: new Date(y, m, 3).toISOString(),
    updatedAt: new Date(y, m, 5).toISOString(),
  },
  {
    id: "p2",
    clientId: "c1",
    title: "Promoção fim de semana",
    caption: "🎉 Sábado é dia de mimo! Traga um amigo e ganhe desconto no segundo café. Válido apenas este sábado!",
    network: "instagram",
    status: "agendado",
    scheduledAt: new Date(y, m, 15, 8, 0).toISOString(),
    hashtags: ["#promoção", "#café", "#fim-de-semana"],
    comments: [
      {
        id: "cm1",
        postId: "p2",
        authorId: "u2",
        authorName: "João Café",
        authorRole: "cliente",
        content: "Pode mudar o desconto para 15% ao invés de 10%?",
        createdAt: new Date(y, m, 10).toISOString(),
      },
    ],
    createdAt: new Date(y, m, 8).toISOString(),
    updatedAt: new Date(y, m, 10).toISOString(),
  },
  {
    id: "p3",
    clientId: "c1",
    title: "Novo produto: Croissant",
    caption: "Novidade quentinha saindo do forno! 🥐 Nosso croissant artesanal chegou para ficar. Manteiga francesa, crocante por fora, macio por dentro.",
    network: "instagram",
    status: "aprovacao",
    scheduledAt: new Date(y, m, 20, 10, 0).toISOString(),
    hashtags: ["#croissant", "#padaria", "#novidade"],
    comments: [],
    createdAt: new Date(y, m, 12).toISOString(),
    updatedAt: new Date(y, m, 12).toISOString(),
  },
  {
    id: "p4",
    clientId: "c1",
    title: "Dica de café",
    caption: "Você sabia que a temperatura ideal para extrair um espresso perfeito é entre 88°C e 96°C? ☕ Aqui no Café do João controlamos cada detalhe!",
    network: "instagram",
    status: "rascunho",
    scheduledAt: new Date(y, m, 25, 14, 0).toISOString(),
    hashtags: ["#dica", "#barista", "#café"],
    comments: [],
    createdAt: new Date(y, m, 14).toISOString(),
    updatedAt: new Date(y, m, 14).toISOString(),
  },
  {
    id: "p5",
    clientId: "c2",
    title: "Aula de pilates - manhã",
    caption: "🧘‍♀️ Começa bem quem se cuida! Nossas turmas da manhã ainda têm vagas. Pilates para todos os níveis. Transforme seu corpo e sua mente.",
    network: "instagram",
    status: "publicado",
    scheduledAt: new Date(y, m, 3, 7, 0).toISOString(),
    publishedAt: new Date(y, m, 3, 7, 0).toISOString(),
    hashtags: ["#pilates", "#saúde", "#fitness"],
    comments: [],
    createdAt: new Date(y, m, 1).toISOString(),
    updatedAt: new Date(y, m, 3).toISOString(),
  },
  {
    id: "p6",
    clientId: "c2",
    title: "Depoimento cliente",
    caption: "\"Após 3 meses de pilates com a Mari, minha postura e disposição mudaram completamente!\" — Carla, 38 anos 💪",
    network: "instagram",
    status: "agendado",
    scheduledAt: new Date(y, m, 18, 9, 0).toISOString(),
    hashtags: ["#depoimento", "#resultado", "#pilates"],
    comments: [],
    createdAt: new Date(y, m, 10).toISOString(),
    updatedAt: new Date(y, m, 10).toISOString(),
  },
  {
    id: "p7",
    clientId: "c3",
    title: "Case de sucesso",
    caption: "Reduzimos em 40% o consumo de energia de uma fábrica em SP usando nossa solução IoT. Sustentabilidade e eficiência andam juntas. Saiba mais.",
    network: "linkedin",
    status: "aprovacao",
    scheduledAt: new Date(y, m, 22, 11, 0).toISOString(),
    hashtags: ["#sustentabilidade", "#IoT", "#tecnologia"],
    comments: [],
    createdAt: new Date(y, m, 15).toISOString(),
    updatedAt: new Date(y, m, 15).toISOString(),
  },
]
